### PR TITLE
Did a little rewriting of the READ Me, let me know if you like it

### PR DESCRIPTION
**Pull request by eegilbert**

### CODE REVIEW

**Comment by gurugio** [comment]
Thank you for taking your time ;-)

**Comment by eegilbert** [comment]
You're welcome. If you're liking the changes, I will do some more proofing
and make suggestions. Feel free to keep the changes you like :)

**Comment by eegilbert** [comment]
also I am learning git, so I may make erroneous pull requests. i will try
and keep this to a minimum.

**Comment by gurugio** [comment]
I thank you in advance ;-)
Don't worry about pull request. We can handle it.

**Pull request merged**
