### PR TITLE
Create 8086arch.md

### PR DESCRIPTION
**Pull request by ghost**
just changed do to does which seems gramaticaly correct.

### CODE REVIEW

**Comment by gurugio** [comment]
Thank you ;-)

**Comment by ghost** [comment]
No thank you :) your sense of humour and love for the matrix kept me
reading and learning

**Comment by ghost** [comment]
hey, any idea when 64 bit ones are going to be translated, I am currently
learning C and ASL from your university :) helps a lot.

On Wed, Jun 14, 2017 at 9:59 PM, Achilles Gaikwad <achillesgaikwad@gmail.com
> wrote:

> No thank you :) your sense of humour and love for the matrix kept me
> reading and learning
>

**Comment by gurugio** [comment]
I'm transferring another document, linux block driver.
I'll start it later.

**Comment by ghost** [comment]
i'll like to read that too!

**Pull request merged**
